[workspace]
authors = ["Lorena Pantano <lorena.pantano@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "nextflow-arcashla"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nextflow = ">=25.10.2,<26"
